### ISSUE TITLE
nb啊nekomio

### ISSUE THREAD

**Issue by orzzz23333** [NekoMio/MineDNS#1]

**Comment by NekoMio** [comment]
????

------------------Original------------------
From: "orzzz"; 
Date: 2021年6月5日(星期六) 中午12:16
To: "NekoMio/MineDNS"; 
Cc: "Subscribed"; 
Subject: [NekoMio/MineDNS] nb啊nekomio (#1)

**Comment by orzzz23333** [comment]
**_### 救命恩人_**

**Comment by orzzz23333** [comment]
help life grate person
